//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteBanGiaySneaker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETHD
    {
        public int MaDH { get; set; }
        public int MaSP { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<decimal> DonGia { get; set; }
        public int MaSize { get; set; }
        public int MaMau { get; set; }
    
        public virtual DONHANG DONHANG { get; set; }
        public virtual SANPHAM SANPHAM { get; set; }
        public virtual MauSac MauSac { get; set; }
        public virtual Size Size { get; set; }
    }
}
